////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace New.Properties {
    
    
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
//    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
//        private static Settings  = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
//        public static Settings Default {
//            get {
//                return defaultInstance;
//            }
//        }
        
//        [global::System.Configuration.ApplicationScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
//        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=p17server.database.windows.net;Initial Catalog=P17DATABASE;User ID=P1" +
//            "7;Password=Hadas@2017")]
//        public string P17DATABASEConnectionString {
//            get {
//                return ((string)(this["P17DATABASEConnectionString"]));
//            }
//        }
//    }
//}
